//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadTest.RService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerInfo", Namespace="http://schemas.datacontract.org/2004/07/Remoting.Contract.Data")]
    [System.SerializableAttribute()]
    public partial class PlayerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExperienceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FriendVerifyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid GuidIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasEnterAlumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasExtendWishField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasPhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsApproveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFirstLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastSceneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MoneyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NickNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassWordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SchoolIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SchoolNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StyleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StyleTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrueNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserSignField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Experience {
            get {
                return this.ExperienceField;
            }
            set {
                if ((this.ExperienceField.Equals(value) != true)) {
                    this.ExperienceField = value;
                    this.RaisePropertyChanged("Experience");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FriendVerify {
            get {
                return this.FriendVerifyField;
            }
            set {
                if ((this.FriendVerifyField.Equals(value) != true)) {
                    this.FriendVerifyField = value;
                    this.RaisePropertyChanged("FriendVerify");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid GuidId {
            get {
                return this.GuidIdField;
            }
            set {
                if ((this.GuidIdField.Equals(value) != true)) {
                    this.GuidIdField = value;
                    this.RaisePropertyChanged("GuidId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasEnterAlum {
            get {
                return this.HasEnterAlumField;
            }
            set {
                if ((this.HasEnterAlumField.Equals(value) != true)) {
                    this.HasEnterAlumField = value;
                    this.RaisePropertyChanged("HasEnterAlum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasExtendWish {
            get {
                return this.HasExtendWishField;
            }
            set {
                if ((this.HasExtendWishField.Equals(value) != true)) {
                    this.HasExtendWishField = value;
                    this.RaisePropertyChanged("HasExtendWish");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasPhoto {
            get {
                return this.HasPhotoField;
            }
            set {
                if ((this.HasPhotoField.Equals(value) != true)) {
                    this.HasPhotoField = value;
                    this.RaisePropertyChanged("HasPhoto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsApprove {
            get {
                return this.IsApproveField;
            }
            set {
                if ((this.IsApproveField.Equals(value) != true)) {
                    this.IsApproveField = value;
                    this.RaisePropertyChanged("IsApprove");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFirstLogin {
            get {
                return this.IsFirstLoginField;
            }
            set {
                if ((this.IsFirstLoginField.Equals(value) != true)) {
                    this.IsFirstLoginField = value;
                    this.RaisePropertyChanged("IsFirstLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastScene {
            get {
                return this.LastSceneField;
            }
            set {
                if ((object.ReferenceEquals(this.LastSceneField, value) != true)) {
                    this.LastSceneField = value;
                    this.RaisePropertyChanged("LastScene");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Level {
            get {
                return this.LevelField;
            }
            set {
                if ((this.LevelField.Equals(value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Money {
            get {
                return this.MoneyField;
            }
            set {
                if ((this.MoneyField.Equals(value) != true)) {
                    this.MoneyField = value;
                    this.RaisePropertyChanged("Money");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NickName {
            get {
                return this.NickNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NickNameField, value) != true)) {
                    this.NickNameField = value;
                    this.RaisePropertyChanged("NickName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassWord {
            get {
                return this.PassWordField;
            }
            set {
                if ((object.ReferenceEquals(this.PassWordField, value) != true)) {
                    this.PassWordField = value;
                    this.RaisePropertyChanged("PassWord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SchoolId {
            get {
                return this.SchoolIdField;
            }
            set {
                if ((this.SchoolIdField.Equals(value) != true)) {
                    this.SchoolIdField = value;
                    this.RaisePropertyChanged("SchoolId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SchoolName {
            get {
                return this.SchoolNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SchoolNameField, value) != true)) {
                    this.SchoolNameField = value;
                    this.RaisePropertyChanged("SchoolName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Sex {
            get {
                return this.SexField;
            }
            set {
                if ((this.SexField.Equals(value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Style {
            get {
                return this.StyleField;
            }
            set {
                if ((object.ReferenceEquals(this.StyleField, value) != true)) {
                    this.StyleField = value;
                    this.RaisePropertyChanged("Style");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StyleType {
            get {
                return this.StyleTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.StyleTypeField, value) != true)) {
                    this.StyleTypeField = value;
                    this.RaisePropertyChanged("StyleType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrueName {
            get {
                return this.TrueNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TrueNameField, value) != true)) {
                    this.TrueNameField = value;
                    this.RaisePropertyChanged("TrueName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserSign {
            get {
                return this.UserSignField;
            }
            set {
                if ((object.ReferenceEquals(this.UserSignField, value) != true)) {
                    this.UserSignField = value;
                    this.RaisePropertyChanged("UserSign");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RService.IPlayerService")]
    public interface IPlayerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/Login", ReplyAction="http://tempuri.org/IPlayerService/LoginResponse")]
        RoadTest.RService.PlayerInfo Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/GetPlayerFriends", ReplyAction="http://tempuri.org/IPlayerService/GetPlayerFriendsResponse")]
        RoadTest.RService.PlayerInfo[] GetPlayerFriends(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/GetPlayerFriendsOwerId", ReplyAction="http://tempuri.org/IPlayerService/GetPlayerFriendsOwerIdResponse")]
        int[] GetPlayerFriendsOwerId(int id, int state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/UpdatePlayer", ReplyAction="http://tempuri.org/IPlayerService/UpdatePlayerResponse")]
        bool UpdatePlayer(RoadTest.RService.PlayerInfo player);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IPlayerServiceChannel : RoadTest.RService.IPlayerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class PlayerServiceClient : System.ServiceModel.ClientBase<RoadTest.RService.IPlayerService>, RoadTest.RService.IPlayerService {
        
        public PlayerServiceClient() {
        }
        
        public PlayerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlayerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RoadTest.RService.PlayerInfo Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public RoadTest.RService.PlayerInfo[] GetPlayerFriends(System.Guid id) {
            return base.Channel.GetPlayerFriends(id);
        }
        
        public int[] GetPlayerFriendsOwerId(int id, int state) {
            return base.Channel.GetPlayerFriendsOwerId(id, state);
        }
        
        public bool UpdatePlayer(RoadTest.RService.PlayerInfo player) {
            return base.Channel.UpdatePlayer(player);
        }
    }
}
